// Kymider — PROOF.md, rendered from the receipts of a real run.
//
// Pure: the receipts, the deployments record and (optionally) the claim
// results go in, Markdown comes out. Nothing here invents a hash: every row
// is a receipt midnight-js returned for a finalized transaction.

import type { TxReceipt } from '../../client/txlog.js';
import type { Deployments } from './deployments.js';
import type { ClaimResult } from './claims.js';
import { LOAN_ROLES, LOAN_SHORT_NAMES, STEP_LIST, stepByLabel } from './flow.js';
import { TX_BY_HASH_QUERY } from './onchain-query.js';

/** Networks whose transactions anyone can look up. */
export const PUBLIC_NETWORKS = ['preview', 'preprod', 'mainnet'] as const;

export const isPublicNetwork = (network: string): boolean =>
  (PUBLIC_NETWORKS as readonly string[]).includes(network);

/**
 * Explorer transaction URL templates by network, with `{txHash}` (or
 * `{txId}`) as the placeholder. Empty on purpose: no explorer URL pattern is
 * confirmed for these networks yet, and a guessed link is worse than none.
 * Set KYMIDER_EXPLORER_TX_URL to add the column without a code change.
 */
export const KNOWN_EXPLORERS: Readonly<Record<string, string>> = {};

export function explorerTemplate(network: string, override?: string): string | undefined {
  const t = override?.trim() || KNOWN_EXPLORERS[network];
  return t && (t.includes('{txHash}') || t.includes('{txId}')) ? t : undefined;
}

export function explorerLink(template: string, r: Pick<TxReceipt, 'txHash' | 'txId'>): string {
  return template.split('{txHash}').join(r.txHash).split('{txId}').join(r.txId);
}

const cell = (s: string): string => s.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
const code = (s: string): string => `\`${s}\``;

/** Display name for a contract address, from its role in the run. */
export function contractNames(d: Deployments): Map<string, string> {
  const names = new Map<string, string>([
    [d.contracts.solvencyProof, 'SolvencyProof'],
    [d.contracts.registry, 'Registry'],
    [d.contracts.loanDirectory, 'LoanDirectory'],
  ]);
  d.contracts.loans.forEach((loan, i) => names.set(loan, LOAN_SHORT_NAMES[i] ?? `Loan ${i + 1}`));
  return names;
}

export type ProofInput = {
  deployments: Deployments;
  receipts: readonly TxReceipt[];
  /** Claim results from the run, if they were checked before writing. */
  claims?: readonly ClaimResult[];
  /** Explorer URL template (see explorerTemplate). */
  explorer?: string;
};

export function renderProofMd({ deployments: d, receipts, claims, explorer }: ProofInput): string {
  const names = contractNames(d);
  const isPublic = isPublicNetwork(d.network);
  const out: string[] = [];

  out.push(`# Kymider on-chain proof: ${d.network}`, '');
  out.push(
    `Generated by \`npm run prove:onchain\` at ${d.generatedAt} from a real run: every hash below is a ` +
      'finalized transaction that midnight-js returned, with its block. Nothing in this file is typed by hand.',
    '',
  );
  if (isPublic) {
    out.push(
      `- Network: **${d.network}** (public Midnight testnet)`,
      `- Indexer: ${d.indexer}`,
      `- Machine-readable record: \`frontend/public/deployments/${d.network}.json\``,
      '',
    );
  } else {
    out.push(
      `> **Local devnet run (${d.network}).** These hashes come from a throwaway chain started in CI;`,
      '> they cannot be looked up on any public network. The public record comes from the',
      '> `Preprod proof` workflow (`.github/workflows/preprod.yml`).',
      '',
      `- Indexer: ${d.indexer}`,
      `- Machine-readable record: \`frontend/public/deployments/${d.network}.json\``,
      '',
    );
  }

  out.push(
    '## What this shows',
    '',
    'A borrower commits their financial facts once, proves solvency to a lender in zero knowledge, and then',
    'borrows **at 110% collateral instead of 150%** because the tier proof (not the facts) reaches the ledger.',
    'Loan A takes that route; loan B skips the proof and is held to 150%. Both are repaid and recorded, and a',
    'third application proves "two repaid Kymider loans" without naming them.',
    '',
  );

  out.push('## Contracts', '', '| Contract | Address |', '|---|---|');
  out.push(`| SolvencyProof (the borrower's instance) | ${code(d.contracts.solvencyProof)} |`);
  out.push(`| Registry (shared index) | ${code(d.contracts.registry)} |`);
  out.push(`| LoanDirectory (shared index and repayment records) | ${code(d.contracts.loanDirectory)} |`);
  d.contracts.loans.forEach((loan, i) => {
    out.push(`| ${cell(LOAN_ROLES[i] ?? `Loan ${i + 1}`)} | ${code(loan)} |`);
  });
  out.push('');

  out.push(`## Transactions (${receipts.length})`, '');
  const header = ['#', 'Step', 'Contract', 'Circuit', 'Tx hash', 'Block'];
  if (explorer) header.push('Explorer');
  out.push(`| ${header.join(' | ')} |`, `|${header.map(() => '---').join('|')}|`);
  receipts.forEach((r, i) => {
    const row = [
      String(i + 1),
      cell(r.label),
      cell(names.get(r.contract) ?? r.contractName),
      code(r.circuit),
      code(r.txHash),
      String(r.blockHeight),
    ];
    if (explorer) row.push(`[view](${explorerLink(explorer, r)})`);
    out.push(`| ${row.join(' | ')} |`);
  });
  out.push('');
  if (!explorer) {
    out.push(
      'No explorer link column: no explorer URL pattern is confirmed for this network, and a guessed link',
      'would be worse than none. Look a hash up on the indexer instead (below).',
      '',
    );
  }

  out.push(
    '## What each step proves, and what stays private',
    '',
    '| Step | Proves (public, checked by the network) | Stays private |',
    '|---|---|---|',
  );
  const seen = new Set(receipts.map((r) => r.label));
  for (const s of STEP_LIST) {
    if (!seen.has(s.label)) continue;
    out.push(`| ${cell(s.label)} | ${cell(s.proves)} | ${cell(s.private)} |`);
  }
  for (const label of seen) {
    if (!stepByLabel(label)) out.push(`| ${cell(label)} | | |`);
  }
  out.push('');

  if (claims && claims.length > 0) {
    out.push(
      '## Claims checked against the chain',
      '',
      'Read back from the indexer after the run, by the same code as `npm run verify:onchain`.',
      '',
      '| Claim | Expected | On-chain | Result |',
      '|---|---|---|---|',
    );
    for (const c of claims) {
      out.push(`| ${cell(c.claim)} | ${cell(c.expected)} | ${cell(c.actual)} | ${c.pass ? 'PASS' : '**FAIL**'} |`);
    }
    out.push('');
  }

  out.push('## Check it yourself', '');
  out.push(
    'Read-only, no wallet: re-reads every contract\'s public state from the indexer, checks each claim above,',
    'and looks up every transaction hash.',
    '',
    '```sh',
    'npm ci',
    d.network === 'preprod' ? 'npm run verify:preprod' : `MIDNIGHT_NETWORK=${d.network} npm run verify:onchain`,
    '```',
    '',
    'Or look up one hash directly on the indexer:',
    '',
    '```sh',
    `curl -s ${d.indexer} -H 'content-type: application/json' \\`,
    `  -d '${JSON.stringify({ query: TX_BY_HASH_QUERY, variables: { offset: { hash: receipts[0]?.txHash ?? '<tx hash>' } } })}'`,
    '```',
    '',
  );

  return `${out.join('\n')}`;
}
