// Kymider — compiled contract exports.
//
// Re-exports the two Wave 1 programs (SolvencyProof per-borrower instance and
// the shared Registry) from the `compact compile` output in ../compiled, and
// wires each to its witnesses + ZK artifacts so midnight-js can run them.
//
// These files are generated by `npm run build:contracts` and are gitignored.

import { CompiledContract } from '@midnight-ntwrk/midnight-js-protocol/compact-js';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { registryWitnesses, solvencyWitnesses } from './witnesses.js';

// --- SolvencyProof --------------------------------------------------------
import {
  Contract as SolvencyProofContract,
  ledger as solvencyLedger,
  pureCircuits as solvencyPureCircuits,
  ClaimStatus,
  AttestationStatus,
} from '../compiled/solvency-proof/contract/index.js';
import type {
  Ledger as SolvencyLedger,
  Witnesses as SolvencyWitnesses,
} from '../compiled/solvency-proof/contract/index.js';

export {
  SolvencyProofContract,
  solvencyLedger,
  solvencyPureCircuits,
  ClaimStatus,
  AttestationStatus,
};
export type { SolvencyLedger, SolvencyWitnesses };

// --- Registry -------------------------------------------------------------
import {
  Contract as RegistryContract,
  ledger as registryLedger,
  pureCircuits as registryPureCircuits,
  BorrowStatus,
} from '../compiled/registry/contract/index.js';
import type {
  Ledger as RegistryLedger,
  Witnesses as RegistryWitnesses,
} from '../compiled/registry/contract/index.js';

export {
  RegistryContract,
  registryLedger,
  registryPureCircuits,
  BorrowStatus,
};
export type { RegistryLedger, RegistryWitnesses };

// --- compiled artifact locations ------------------------------------------

const contractsDir = fileURLToPath(new URL('.', import.meta.url));

export const solvencyZkConfigPath = path.resolve(contractsDir, '..', 'compiled', 'solvency-proof');
export const registryZkConfigPath = path.resolve(contractsDir, '..', 'compiled', 'registry');

export const CompiledSolvencyProofContract = CompiledContract.make(
  'SolvencyProofContract',
  SolvencyProofContract,
).pipe(
  CompiledContract.withWitnesses(solvencyWitnesses),
  CompiledContract.withCompiledFileAssets(solvencyZkConfigPath),
);

export const CompiledRegistryContract = CompiledContract.make(
  'RegistryContract',
  RegistryContract,
).pipe(
  CompiledContract.withWitnesses(registryWitnesses),
  CompiledContract.withCompiledFileAssets(registryZkConfigPath),
);