// Kymider — compiled contract exports.
//
// Re-exports the Wave 1 programs (SolvencyProof per-borrower instance and the
// shared Registry) and the Wave 2 ones (Loan per-loan instance and the shared
// LoanDirectory) from the `compact compile` output in ../compiled, and
// wires each to its witnesses + ZK artifacts so midnight-js can run them.
//
// These files are generated by `npm run build:contracts` and are gitignored.

import { CompiledContract } from '@midnight-ntwrk/midnight-js-protocol/compact-js';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  loanDirectoryWitnesses,
  loanWitnesses,
  registryWitnesses,
  solvencyWitnesses,
} from './witnesses.js';

// --- SolvencyProof --------------------------------------------------------
import {
  Contract as SolvencyProofContract,
  ledger as solvencyLedger,
  pureCircuits as solvencyPureCircuits,
  ClaimStatus,
  AttestationStatus,
} from '../compiled/solvency-proof/contract/index.js';
import type {
  Ledger as SolvencyLedger,
  Witnesses as SolvencyWitnesses,
} from '../compiled/solvency-proof/contract/index.js';

export {
  SolvencyProofContract,
  solvencyLedger,
  solvencyPureCircuits,
  ClaimStatus,
  AttestationStatus,
};
export type { SolvencyLedger, SolvencyWitnesses };

// --- Registry -------------------------------------------------------------
import {
  Contract as RegistryContract,
  ledger as registryLedger,
  pureCircuits as registryPureCircuits,
  BorrowStatus,
} from '../compiled/registry/contract/index.js';
import type {
  Ledger as RegistryLedger,
  Witnesses as RegistryWitnesses,
} from '../compiled/registry/contract/index.js';

export {
  RegistryContract,
  registryLedger,
  registryPureCircuits,
  BorrowStatus,
};
export type { RegistryLedger, RegistryWitnesses };

// --- Loan -----------------------------------------------------------------
import {
  Contract as LoanContract,
  ledger as loanLedger,
  pureCircuits as loanPureCircuits,
  LoanStatus,
  Tier,
} from '../compiled/loan/contract/index.js';
import type {
  Ledger as LoanLedger,
  Witnesses as LoanWitnesses,
  LoanTerms,
  Quote,
} from '../compiled/loan/contract/index.js';

export { LoanContract, loanLedger, loanPureCircuits, LoanStatus, Tier };
export type { LoanLedger, LoanWitnesses, LoanTerms, Quote };

// --- LoanDirectory --------------------------------------------------------
import {
  Contract as LoanDirectoryContract,
  ledger as loanDirectoryLedger,
  pureCircuits as loanDirectoryPureCircuits,
  ListingStatus,
} from '../compiled/loan-directory/contract/index.js';
import type {
  Ledger as LoanDirectoryLedger,
  Witnesses as LoanDirectoryWitnesses,
  Listing,
} from '../compiled/loan-directory/contract/index.js';

export { LoanDirectoryContract, loanDirectoryLedger, loanDirectoryPureCircuits, ListingStatus };
export type { LoanDirectoryLedger, LoanDirectoryWitnesses, Listing };

// --- compiled artifact locations ------------------------------------------

const contractsDir = fileURLToPath(new URL('.', import.meta.url));

export const solvencyZkConfigPath = path.resolve(contractsDir, '..', 'compiled', 'solvency-proof');
export const registryZkConfigPath = path.resolve(contractsDir, '..', 'compiled', 'registry');
export const loanZkConfigPath = path.resolve(contractsDir, '..', 'compiled', 'loan');
export const loanDirectoryZkConfigPath = path.resolve(contractsDir, '..', 'compiled', 'loan-directory');

export const CompiledSolvencyProofContract = CompiledContract.make(
  'SolvencyProofContract',
  SolvencyProofContract,
).pipe(
  CompiledContract.withWitnesses(solvencyWitnesses),
  CompiledContract.withCompiledFileAssets(solvencyZkConfigPath),
);

export const CompiledRegistryContract = CompiledContract.make(
  'RegistryContract',
  RegistryContract,
).pipe(
  CompiledContract.withWitnesses(registryWitnesses),
  CompiledContract.withCompiledFileAssets(registryZkConfigPath),
);

export const CompiledLoanContract = CompiledContract.make('LoanContract', LoanContract).pipe(
  CompiledContract.withWitnesses(loanWitnesses),
  CompiledContract.withCompiledFileAssets(loanZkConfigPath),
);

export const CompiledLoanDirectoryContract = CompiledContract.make(
  'LoanDirectoryContract',
  LoanDirectoryContract,
).pipe(
  CompiledContract.withWitnesses(loanDirectoryWitnesses),
  CompiledContract.withCompiledFileAssets(loanDirectoryZkConfigPath),
);
